[package]
name = "tcp"
version = "0.1.0"
authors = ["xl000 <l_xb@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
