-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local timestamp_pb = require("timestamp_pb")
module('addressbook_pb')


local PERSON = protobuf.Descriptor();
local PERSON_PHONENUMBER = protobuf.Descriptor();
local PERSON_PHONENUMBER_NUMBER_FIELD = protobuf.FieldDescriptor();
local PERSON_PHONENUMBER_TYPE_FIELD = protobuf.FieldDescriptor();
local PERSON_PHONETYPE = protobuf.EnumDescriptor();
local PERSON_PHONETYPE_MOBILE_ENUM = protobuf.EnumValueDescriptor();
local PERSON_PHONETYPE_HOME_ENUM = protobuf.EnumValueDescriptor();
local PERSON_PHONETYPE_WORK_ENUM = protobuf.EnumValueDescriptor();
local PERSON_NAME_FIELD = protobuf.FieldDescriptor();
local PERSON_ID_FIELD = protobuf.FieldDescriptor();
local PERSON_EMAIL_FIELD = protobuf.FieldDescriptor();
local PERSON_PHONES_FIELD = protobuf.FieldDescriptor();
local PERSON_TEST_UINT64_FIELD = protobuf.FieldDescriptor();
local PERSON_TEST_FLOAT_FIELD = protobuf.FieldDescriptor();
local PERSON_TEST_DOUBLE_FIELD = protobuf.FieldDescriptor();
local PERSON_LAST_UPDATED_FIELD = protobuf.FieldDescriptor();
local ADDRESSBOOK = protobuf.Descriptor();
local ADDRESSBOOK_PEOPLE_FIELD = protobuf.FieldDescriptor();

PERSON_PHONENUMBER_NUMBER_FIELD.name = "number"
PERSON_PHONENUMBER_NUMBER_FIELD.full_name = ".tutorial.Person.PhoneNumber.number"
PERSON_PHONENUMBER_NUMBER_FIELD.number = 1
PERSON_PHONENUMBER_NUMBER_FIELD.index = 0
PERSON_PHONENUMBER_NUMBER_FIELD.label = 1
PERSON_PHONENUMBER_NUMBER_FIELD.has_default_value = false
PERSON_PHONENUMBER_NUMBER_FIELD.default_value = ""
PERSON_PHONENUMBER_NUMBER_FIELD.type = 9
PERSON_PHONENUMBER_NUMBER_FIELD.cpp_type = 9

PERSON_PHONENUMBER_TYPE_FIELD.name = "type"
PERSON_PHONENUMBER_TYPE_FIELD.full_name = ".tutorial.Person.PhoneNumber.type"
PERSON_PHONENUMBER_TYPE_FIELD.number = 2
PERSON_PHONENUMBER_TYPE_FIELD.index = 1
PERSON_PHONENUMBER_TYPE_FIELD.label = 1
PERSON_PHONENUMBER_TYPE_FIELD.has_default_value = false
PERSON_PHONENUMBER_TYPE_FIELD.default_value = nil
PERSON_PHONENUMBER_TYPE_FIELD.enum_type = _PERSON_PHONETYPE
PERSON_PHONENUMBER_TYPE_FIELD.type = 14
PERSON_PHONENUMBER_TYPE_FIELD.cpp_type = 8

PERSON_PHONENUMBER.name = "PhoneNumber"
PERSON_PHONENUMBER.full_name = ".tutorial.Person.PhoneNumber"
PERSON_PHONENUMBER.nested_types = {}
PERSON_PHONENUMBER.enum_types = {}
PERSON_PHONENUMBER.fields = {PERSON_PHONENUMBER_NUMBER_FIELD, PERSON_PHONENUMBER_TYPE_FIELD}
PERSON_PHONENUMBER.is_extendable = false
PERSON_PHONENUMBER.extensions = {}
PERSON_PHONENUMBER.containing_type = PERSON
PERSON_PHONETYPE_MOBILE_ENUM.name = "MOBILE"
PERSON_PHONETYPE_MOBILE_ENUM.index = 0
PERSON_PHONETYPE_MOBILE_ENUM.number = 0
PERSON_PHONETYPE_HOME_ENUM.name = "HOME"
PERSON_PHONETYPE_HOME_ENUM.index = 1
PERSON_PHONETYPE_HOME_ENUM.number = 1
PERSON_PHONETYPE_WORK_ENUM.name = "WORK"
PERSON_PHONETYPE_WORK_ENUM.index = 2
PERSON_PHONETYPE_WORK_ENUM.number = 2
PERSON_PHONETYPE.name = "PhoneType"
PERSON_PHONETYPE.full_name = ".tutorial.Person.PhoneType"
PERSON_PHONETYPE.values = {PERSON_PHONETYPE_MOBILE_ENUM,PERSON_PHONETYPE_HOME_ENUM,PERSON_PHONETYPE_WORK_ENUM}
PERSON_NAME_FIELD.name = "name"
PERSON_NAME_FIELD.full_name = ".tutorial.Person.name"
PERSON_NAME_FIELD.number = 1
PERSON_NAME_FIELD.index = 0
PERSON_NAME_FIELD.label = 1
PERSON_NAME_FIELD.has_default_value = false
PERSON_NAME_FIELD.default_value = ""
PERSON_NAME_FIELD.type = 9
PERSON_NAME_FIELD.cpp_type = 9

PERSON_ID_FIELD.name = "id"
PERSON_ID_FIELD.full_name = ".tutorial.Person.id"
PERSON_ID_FIELD.number = 2
PERSON_ID_FIELD.index = 1
PERSON_ID_FIELD.label = 1
PERSON_ID_FIELD.has_default_value = false
PERSON_ID_FIELD.default_value = 0
PERSON_ID_FIELD.type = 5
PERSON_ID_FIELD.cpp_type = 1

PERSON_EMAIL_FIELD.name = "email"
PERSON_EMAIL_FIELD.full_name = ".tutorial.Person.email"
PERSON_EMAIL_FIELD.number = 3
PERSON_EMAIL_FIELD.index = 2
PERSON_EMAIL_FIELD.label = 1
PERSON_EMAIL_FIELD.has_default_value = false
PERSON_EMAIL_FIELD.default_value = ""
PERSON_EMAIL_FIELD.type = 9
PERSON_EMAIL_FIELD.cpp_type = 9

PERSON_PHONES_FIELD.name = "phones"
PERSON_PHONES_FIELD.full_name = ".tutorial.Person.phones"
PERSON_PHONES_FIELD.number = 4
PERSON_PHONES_FIELD.index = 3
PERSON_PHONES_FIELD.label = 3
PERSON_PHONES_FIELD.has_default_value = false
PERSON_PHONES_FIELD.default_value = {}
PERSON_PHONES_FIELD.message_type = PERSON_PHONENUMBER
PERSON_PHONES_FIELD.type = 11
PERSON_PHONES_FIELD.cpp_type = 10

PERSON_TEST_UINT64_FIELD.name = "test_uint64"
PERSON_TEST_UINT64_FIELD.full_name = ".tutorial.Person.test_uint64"
PERSON_TEST_UINT64_FIELD.number = 5
PERSON_TEST_UINT64_FIELD.index = 4
PERSON_TEST_UINT64_FIELD.label = 3
PERSON_TEST_UINT64_FIELD.has_default_value = false
PERSON_TEST_UINT64_FIELD.default_value = {}
PERSON_TEST_UINT64_FIELD.type = 4
PERSON_TEST_UINT64_FIELD.cpp_type = 4

PERSON_TEST_FLOAT_FIELD.name = "test_float"
PERSON_TEST_FLOAT_FIELD.full_name = ".tutorial.Person.test_float"
PERSON_TEST_FLOAT_FIELD.number = 6
PERSON_TEST_FLOAT_FIELD.index = 5
PERSON_TEST_FLOAT_FIELD.label = 3
PERSON_TEST_FLOAT_FIELD.has_default_value = false
PERSON_TEST_FLOAT_FIELD.default_value = {}
PERSON_TEST_FLOAT_FIELD.type = 2
PERSON_TEST_FLOAT_FIELD.cpp_type = 6

PERSON_TEST_DOUBLE_FIELD.name = "test_double"
PERSON_TEST_DOUBLE_FIELD.full_name = ".tutorial.Person.test_double"
PERSON_TEST_DOUBLE_FIELD.number = 7
PERSON_TEST_DOUBLE_FIELD.index = 6
PERSON_TEST_DOUBLE_FIELD.label = 3
PERSON_TEST_DOUBLE_FIELD.has_default_value = false
PERSON_TEST_DOUBLE_FIELD.default_value = {}
PERSON_TEST_DOUBLE_FIELD.type = 1
PERSON_TEST_DOUBLE_FIELD.cpp_type = 5

PERSON_LAST_UPDATED_FIELD.name = "last_updated"
PERSON_LAST_UPDATED_FIELD.full_name = ".tutorial.Person.last_updated"
PERSON_LAST_UPDATED_FIELD.number = 8
PERSON_LAST_UPDATED_FIELD.index = 7
PERSON_LAST_UPDATED_FIELD.label = 1
PERSON_LAST_UPDATED_FIELD.has_default_value = false
PERSON_LAST_UPDATED_FIELD.default_value = nil
PERSON_LAST_UPDATED_FIELD.message_type = TIMESTAMP_PB_TIMESTAMP
PERSON_LAST_UPDATED_FIELD.type = 11
PERSON_LAST_UPDATED_FIELD.cpp_type = 10

PERSON.name = "Person"
PERSON.full_name = ".tutorial.Person"
PERSON.nested_types = {PERSON_PHONENUMBER}
PERSON.enum_types = {PERSON_PHONETYPE}
PERSON.fields = {PERSON_NAME_FIELD, PERSON_ID_FIELD, PERSON_EMAIL_FIELD, PERSON_PHONES_FIELD, PERSON_TEST_UINT64_FIELD, PERSON_TEST_FLOAT_FIELD, PERSON_TEST_DOUBLE_FIELD, PERSON_LAST_UPDATED_FIELD}
PERSON.is_extendable = false
PERSON.extensions = {}
ADDRESSBOOK_PEOPLE_FIELD.name = "people"
ADDRESSBOOK_PEOPLE_FIELD.full_name = ".tutorial.AddressBook.people"
ADDRESSBOOK_PEOPLE_FIELD.number = 1
ADDRESSBOOK_PEOPLE_FIELD.index = 0
ADDRESSBOOK_PEOPLE_FIELD.label = 3
ADDRESSBOOK_PEOPLE_FIELD.has_default_value = false
ADDRESSBOOK_PEOPLE_FIELD.default_value = {}
ADDRESSBOOK_PEOPLE_FIELD.message_type = PERSON
ADDRESSBOOK_PEOPLE_FIELD.type = 11
ADDRESSBOOK_PEOPLE_FIELD.cpp_type = 10

ADDRESSBOOK.name = "AddressBook"
ADDRESSBOOK.full_name = ".tutorial.AddressBook"
ADDRESSBOOK.nested_types = {}
ADDRESSBOOK.enum_types = {}
ADDRESSBOOK.fields = {ADDRESSBOOK_PEOPLE_FIELD}
ADDRESSBOOK.is_extendable = false
ADDRESSBOOK.extensions = {}

AddressBook = protobuf.Message(ADDRESSBOOK)
Person = protobuf.Message(PERSON)
Person.PhoneNumber = protobuf.Message(PERSON_PHONENUMBER)

