-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.PROFILE = protobuf.Descriptor()
module.PROFILE_NICK_NAME_FIELD = protobuf.FieldDescriptor()
module.PROFILE_ICON_FIELD = protobuf.FieldDescriptor()
module.PERSON = protobuf.Descriptor()
module.PERSON_PHONENUMBER = protobuf.Descriptor()
module.PERSON_PHONENUMBER_NUMBER_FIELD = protobuf.FieldDescriptor()
module.PERSON_PHONENUMBER_TYPE_FIELD = protobuf.FieldDescriptor()
module.PERSON_PHONETYPE = protobuf.EnumDescriptor()
module.PERSON_PHONETYPE_MOBILE_ENUM = protobuf.EnumValueDescriptor()
module.PERSON_PHONETYPE_HOME_ENUM = protobuf.EnumValueDescriptor()
module.PERSON_PHONETYPE_WORK_ENUM = protobuf.EnumValueDescriptor()
module.PERSON_NAME_FIELD = protobuf.FieldDescriptor()
module.PERSON_ID_FIELD = protobuf.FieldDescriptor()
module.PERSON_EMAIL_FIELD = protobuf.FieldDescriptor()
module.PERSON_PHONE_FIELD = protobuf.FieldDescriptor()
module.PERSON_TEST_FIELD = protobuf.FieldDescriptor()
module.PERSON_PROFILE_FIELD = protobuf.FieldDescriptor()
module.EXT = protobuf.Descriptor()
module.EXT_TEST_FIELD = protobuf.FieldDescriptor()
module.ADDRESSBOOK = protobuf.Descriptor()
module.ADDRESSBOOK_PERSON_FIELD = protobuf.FieldDescriptor()

module.PROFILE_NICK_NAME_FIELD.name = 'nick_name'
module.PROFILE_NICK_NAME_FIELD.full_name = '.tutorial.Profile.nick_name'
module.PROFILE_NICK_NAME_FIELD.number = 1
module.PROFILE_NICK_NAME_FIELD.index = 0
module.PROFILE_NICK_NAME_FIELD.label = 1
module.PROFILE_NICK_NAME_FIELD.has_default_value = false
module.PROFILE_NICK_NAME_FIELD.default_value = ''
module.PROFILE_NICK_NAME_FIELD.type = 9
module.PROFILE_NICK_NAME_FIELD.cpp_type = 9

module.PROFILE_ICON_FIELD.name = 'icon'
module.PROFILE_ICON_FIELD.full_name = '.tutorial.Profile.icon'
module.PROFILE_ICON_FIELD.number = 2
module.PROFILE_ICON_FIELD.index = 1
module.PROFILE_ICON_FIELD.label = 1
module.PROFILE_ICON_FIELD.has_default_value = false
module.PROFILE_ICON_FIELD.default_value = ''
module.PROFILE_ICON_FIELD.type = 9
module.PROFILE_ICON_FIELD.cpp_type = 9

module.PROFILE.name = 'Profile'
module.PROFILE.full_name = '.tutorial.Profile'
module.PROFILE.nested_types = {}
module.PROFILE.enum_types = {}
module.PROFILE.fields = {module.PROFILE_NICK_NAME_FIELD, module.PROFILE_ICON_FIELD}
module.PROFILE.is_extendable = false
module.PROFILE.extensions = {}
module.PERSON_PHONENUMBER_NUMBER_FIELD.name = 'number'
module.PERSON_PHONENUMBER_NUMBER_FIELD.full_name = '.tutorial.Person.PhoneNumber.number'
module.PERSON_PHONENUMBER_NUMBER_FIELD.number = 1
module.PERSON_PHONENUMBER_NUMBER_FIELD.index = 0
module.PERSON_PHONENUMBER_NUMBER_FIELD.label = 2
module.PERSON_PHONENUMBER_NUMBER_FIELD.has_default_value = false
module.PERSON_PHONENUMBER_NUMBER_FIELD.default_value = ''
module.PERSON_PHONENUMBER_NUMBER_FIELD.type = 9
module.PERSON_PHONENUMBER_NUMBER_FIELD.cpp_type = 9

module.PERSON_PHONENUMBER_TYPE_FIELD.name = 'type'
module.PERSON_PHONENUMBER_TYPE_FIELD.full_name = '.tutorial.Person.PhoneNumber.type'
module.PERSON_PHONENUMBER_TYPE_FIELD.number = 2
module.PERSON_PHONENUMBER_TYPE_FIELD.index = 1
module.PERSON_PHONENUMBER_TYPE_FIELD.label = 1
module.PERSON_PHONENUMBER_TYPE_FIELD.has_default_value = true
module.PERSON_PHONENUMBER_TYPE_FIELD.default_value = HOME
module.PERSON_PHONENUMBER_TYPE_FIELD.enum_type = module.PERSON_PHONETYPE
module.PERSON_PHONENUMBER_TYPE_FIELD.type = 14
module.PERSON_PHONENUMBER_TYPE_FIELD.cpp_type = 8

module.PERSON_PHONENUMBER.name = 'PhoneNumber'
module.PERSON_PHONENUMBER.full_name = '.tutorial.Person.PhoneNumber'
module.PERSON_PHONENUMBER.nested_types = {}
module.PERSON_PHONENUMBER.enum_types = {}
module.PERSON_PHONENUMBER.fields = {module.PERSON_PHONENUMBER_NUMBER_FIELD, module.PERSON_PHONENUMBER_TYPE_FIELD}
module.PERSON_PHONENUMBER.is_extendable = false
module.PERSON_PHONENUMBER.extensions = {}
module.PERSON_PHONENUMBER.containing_type = PERSON
module.PERSON_PHONETYPE_MOBILE_ENUM.name = 'MOBILE'
module.PERSON_PHONETYPE_MOBILE_ENUM.index = 0
module.PERSON_PHONETYPE_MOBILE_ENUM.number = 0
module.PERSON_PHONETYPE_HOME_ENUM.name = 'HOME'
module.PERSON_PHONETYPE_HOME_ENUM.index = 1
module.PERSON_PHONETYPE_HOME_ENUM.number = 1
module.PERSON_PHONETYPE_WORK_ENUM.name = 'WORK'
module.PERSON_PHONETYPE_WORK_ENUM.index = 2
module.PERSON_PHONETYPE_WORK_ENUM.number = 2
module.PERSON_PHONETYPE.name = 'PhoneType'
module.PERSON_PHONETYPE.full_name = '.tutorial.Person.PhoneType'
module.PERSON_PHONETYPE.values = {PERSON_PHONETYPE_MOBILE_ENUM,PERSON_PHONETYPE_HOME_ENUM,PERSON_PHONETYPE_WORK_ENUM}
module.PERSON_NAME_FIELD.name = 'name'
module.PERSON_NAME_FIELD.full_name = '.tutorial.Person.name'
module.PERSON_NAME_FIELD.number = 1
module.PERSON_NAME_FIELD.index = 0
module.PERSON_NAME_FIELD.label = 2
module.PERSON_NAME_FIELD.has_default_value = false
module.PERSON_NAME_FIELD.default_value = ''
module.PERSON_NAME_FIELD.type = 9
module.PERSON_NAME_FIELD.cpp_type = 9

module.PERSON_ID_FIELD.name = 'id'
module.PERSON_ID_FIELD.full_name = '.tutorial.Person.id'
module.PERSON_ID_FIELD.number = 2
module.PERSON_ID_FIELD.index = 1
module.PERSON_ID_FIELD.label = 2
module.PERSON_ID_FIELD.has_default_value = false
module.PERSON_ID_FIELD.default_value = 0
module.PERSON_ID_FIELD.type = 5
module.PERSON_ID_FIELD.cpp_type = 1

module.PERSON_EMAIL_FIELD.name = 'email'
module.PERSON_EMAIL_FIELD.full_name = '.tutorial.Person.email'
module.PERSON_EMAIL_FIELD.number = 3
module.PERSON_EMAIL_FIELD.index = 2
module.PERSON_EMAIL_FIELD.label = 1
module.PERSON_EMAIL_FIELD.has_default_value = false
module.PERSON_EMAIL_FIELD.default_value = ''
module.PERSON_EMAIL_FIELD.type = 9
module.PERSON_EMAIL_FIELD.cpp_type = 9

module.PERSON_PHONE_FIELD.name = 'phone'
module.PERSON_PHONE_FIELD.full_name = '.tutorial.Person.phone'
module.PERSON_PHONE_FIELD.number = 4
module.PERSON_PHONE_FIELD.index = 3
module.PERSON_PHONE_FIELD.label = 3
module.PERSON_PHONE_FIELD.has_default_value = false
module.PERSON_PHONE_FIELD.default_value = {}
module.PERSON_PHONE_FIELD.message_type = module.PERSON_PHONENUMBER
module.PERSON_PHONE_FIELD.type = 11
module.PERSON_PHONE_FIELD.cpp_type = 10

module.PERSON_TEST_FIELD.name = 'test'
module.PERSON_TEST_FIELD.full_name = '.tutorial.Person.test'
module.PERSON_TEST_FIELD.number = 5
module.PERSON_TEST_FIELD.index = 4
module.PERSON_TEST_FIELD.label = 3
module.PERSON_TEST_FIELD.has_default_value = false
module.PERSON_TEST_FIELD.default_value = {}
module.PERSON_TEST_FIELD.type = 5
module.PERSON_TEST_FIELD.cpp_type = 1

module.PERSON_PROFILE_FIELD.name = 'profile'
module.PERSON_PROFILE_FIELD.full_name = '.tutorial.Person.profile'
module.PERSON_PROFILE_FIELD.number = 6
module.PERSON_PROFILE_FIELD.index = 5
module.PERSON_PROFILE_FIELD.label = 1
module.PERSON_PROFILE_FIELD.has_default_value = false
module.PERSON_PROFILE_FIELD.default_value = nil
module.PERSON_PROFILE_FIELD.message_type = module.PROFILE
module.PERSON_PROFILE_FIELD.type = 11
module.PERSON_PROFILE_FIELD.cpp_type = 10

module.PERSON.name = 'Person'
module.PERSON.full_name = '.tutorial.Person'
module.PERSON.nested_types = {module.PERSON_PHONENUMBER}
module.PERSON.enum_types = {module.PERSON_PHONETYPE}
module.PERSON.fields = {module.PERSON_NAME_FIELD, module.PERSON_ID_FIELD, module.PERSON_EMAIL_FIELD, module.PERSON_PHONE_FIELD, module.PERSON_TEST_FIELD, module.PERSON_PROFILE_FIELD}
module.PERSON.is_extendable = true
module.PERSON.extensions = {}
module.EXT_TEST_FIELD.name = 'test'
module.EXT_TEST_FIELD.full_name = '.tutorial.Ext.test'
module.EXT_TEST_FIELD.number = 10
module.EXT_TEST_FIELD.index = 0
module.EXT_TEST_FIELD.label = 1
module.EXT_TEST_FIELD.has_default_value = false
module.EXT_TEST_FIELD.default_value = 0
module.EXT_TEST_FIELD.type = 5
module.EXT_TEST_FIELD.cpp_type = 1

module.EXT.name = 'Ext'
module.EXT.full_name = '.tutorial.Ext'
module.EXT.nested_types = {}
module.EXT.enum_types = {}
module.EXT.fields = {}
module.EXT.is_extendable = false
module.EXT.extensions = {module.EXT_TEST_FIELD}
module.ADDRESSBOOK_PERSON_FIELD.name = 'person'
module.ADDRESSBOOK_PERSON_FIELD.full_name = '.tutorial.AddressBook.person'
module.ADDRESSBOOK_PERSON_FIELD.number = 1
module.ADDRESSBOOK_PERSON_FIELD.index = 0
module.ADDRESSBOOK_PERSON_FIELD.label = 3
module.ADDRESSBOOK_PERSON_FIELD.has_default_value = false
module.ADDRESSBOOK_PERSON_FIELD.default_value = {}
module.ADDRESSBOOK_PERSON_FIELD.message_type = module.PERSON
module.ADDRESSBOOK_PERSON_FIELD.type = 11
module.ADDRESSBOOK_PERSON_FIELD.cpp_type = 10

module.ADDRESSBOOK.name = 'AddressBook'
module.ADDRESSBOOK.full_name = '.tutorial.AddressBook'
module.ADDRESSBOOK.nested_types = {}
module.ADDRESSBOOK.enum_types = {}
module.ADDRESSBOOK.fields = {module.ADDRESSBOOK_PERSON_FIELD}
module.ADDRESSBOOK.is_extendable = false
module.ADDRESSBOOK.extensions = {}

module.AddressBook = protobuf.Message(module.ADDRESSBOOK)
module.Ext = protobuf.Message(module.EXT)
module.Person = protobuf.Message(module.PERSON)
module.Person.PhoneNumber = protobuf.Message(module.PERSON_PHONENUMBER)
module.Profile = protobuf.Message(module.PROFILE)

Person.RegisterExtension(EXT_TEST_FIELD)

module.MESSAGE_TYPES = {'Profile','Person','Ext','AddressBook'}
module.ENUM_TYPES = {}

return module
