-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.TIMESTAMP = protobuf.Descriptor()
module.TIMESTAMP_SECONDS_FIELD = protobuf.FieldDescriptor()
module.TIMESTAMP_NANOS_FIELD = protobuf.FieldDescriptor()

module.TIMESTAMP_SECONDS_FIELD.name = 'seconds'
module.TIMESTAMP_SECONDS_FIELD.full_name = '.google.protobuf.Timestamp.seconds'
module.TIMESTAMP_SECONDS_FIELD.number = 1
module.TIMESTAMP_SECONDS_FIELD.index = 0
module.TIMESTAMP_SECONDS_FIELD.label = 1
module.TIMESTAMP_SECONDS_FIELD.has_default_value = false
module.TIMESTAMP_SECONDS_FIELD.default_value = 0
module.TIMESTAMP_SECONDS_FIELD.type = 3
module.TIMESTAMP_SECONDS_FIELD.cpp_type = 2

module.TIMESTAMP_NANOS_FIELD.name = 'nanos'
module.TIMESTAMP_NANOS_FIELD.full_name = '.google.protobuf.Timestamp.nanos'
module.TIMESTAMP_NANOS_FIELD.number = 2
module.TIMESTAMP_NANOS_FIELD.index = 1
module.TIMESTAMP_NANOS_FIELD.label = 1
module.TIMESTAMP_NANOS_FIELD.has_default_value = false
module.TIMESTAMP_NANOS_FIELD.default_value = 0
module.TIMESTAMP_NANOS_FIELD.type = 5
module.TIMESTAMP_NANOS_FIELD.cpp_type = 1

module.TIMESTAMP.name = 'Timestamp'
module.TIMESTAMP.full_name = '.google.protobuf.Timestamp'
module.TIMESTAMP.nested_types = {}
module.TIMESTAMP.enum_types = {}
module.TIMESTAMP.fields = {module.TIMESTAMP_SECONDS_FIELD, module.TIMESTAMP_NANOS_FIELD}
module.TIMESTAMP.is_extendable = false
module.TIMESTAMP.extensions = {}

module.Timestamp = protobuf.Message(module.TIMESTAMP)


module.MESSAGE_TYPES = {'Timestamp'}
module.ENUM_TYPES = {}

return module
